name: Docker Image CI

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: us-east-1
  ECR_REGISTRY: public.ecr.aws/s1p6w2l2
  DOCKER_TAG_NAME: devjobs-angular

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: myGitHubActions

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push image to Amazon ECR Public
        run: |
          docker build -t ${{env.DOCKER_TAG_NAME}} .
          docker tag ${{env.DOCKER_TAG_NAME}}:latest ${{env.ECR_REGISTRY}}/${{env.DOCKER_TAG_NAME}}:${{ github.sha }}
          docker push ${{env.ECR_REGISTRY}}/${{env.DOCKER_TAG_NAME}}:${{ github.sha }}
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition devjobs-task-definition --query taskDefinition > task-definition.json --region us-east-1
